version: '3'

services:
  
    ### java Batch server ###
  java01:
      image: openjdk:8-jdk-alpine
      container_name: java
      ports:
        - "8083:8083"
      command: java -jar /home/opc/puneet/myapp.jar

  redis:
      image: redis:5-alpine
      container_name: redis
      hostname: redis
      ports:
        - "6379:6379"
      command: redis-server /home/opc/puneet/redis.conf


  